# Joins & Merges in pandas
In pandas, the primary methods for combining data are `merge()`, `join()` & `concat()`. <br>
The best method to use depends on whether you want to combine based on shared columns (keys), row indices, or simply stack the dataframes

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## The `pd.merge()` method
The pd.merge() function is the most flexible method, performing SQL-style join operations based on common columns or indices. It is used for combining dataframes where the relationship between rows is based on shared key values. Important params are:<br>
`left` - The first df on the left<br>
`right` - second df on the right<br>
`on` - the common column in both the tables<br>
`how` - type of join to be implemented ((default)inner/ left/ right/ outer/ cross) etc.

**Syntax could be -**<br>
`pd.merge(left=T1df , right= T2df, on="col_name", how= )` OR

`T1df.merge(T2df, on="col_name", how= )` 

>Working on data on various wards of the city of Chicago -- office locations , census, land use

In [11]:
# Loading the offices & census datasets
offices = pd.read_pickle("./datasets_joins_merges/ward.p")

census= pd.read_pickle("./datasets_joins_merges/census.p")
print(f"{offices.shape} and {census.shape}" )

(50, 4) and (50, 6)

In [14]:
offices.head()

  ward            alderman                          address    zip
0    1  Proco "Joe" Moreno        2058 NORTH WESTERN AVENUE  60647
1    2       Brian Hopkins       1400 NORTH  ASHLAND AVENUE  60622
2    3          Pat Dowell          5046 SOUTH STATE STREET  60609
3    4    William D. Burns  435 EAST 35TH STREET, 1ST FLOOR  60616
4    5  Leslie A. Hairston            2325 EAST 71ST STREET  60649

In [ ]:
census.head()

,ward,pop_2000,pop_2010,change,address,zip
0,1,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637

Merging the offices with census table using the **common** "ward" column . This will give a unified table that shows ward office locations , the alderman of that ward , along with the population census

In [15]:
offices_census = pd.merge(left=offices , right= census , how="inner" , on="ward")
offices_census.head()

,ward,alderman,address_x,zip_x,pop_2000,pop_2010,change,address_y,zip_y
0,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,Pat Dowell,5046 SOUTH STATE STREET,60609,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,William D. Burns,"435 EAST 35TH STREET, 1ST FLOOR",60616,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,Leslie A. Hairston,2325 EAST 71ST STREET,60649,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637